# Generated by Django 5.0.4 on 2024-06-14 08:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("services", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="serviceimage",
            name="service",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="images",
                to="services.service",
                verbose_name="Услуга",
            ),
        ),
        migrations.CreateModel(
            name="Type",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "title",
                    models.CharField(max_length=50, verbose_name="Название"),
                ),
                (
                    "category",
                    models.CharField(
                        choices=[
                            ("Красота и здоровье", "Beauty"),
                            ("Спорт", "Sport"),
                            ("Домашние животные", "Pets"),
                            ("Для детей", "Children"),
                            ("Ремонт", "Repair"),
                            ("Другое", "Other"),
                        ],
                        max_length=50,
                        verbose_name="Вид услуги",
                    ),
                ),
            ],
            options={
                "verbose_name": "Тип услуги",
                "verbose_name_plural": "Типы услуг",
                "ordering": ["category", "title"],
                "index_together": {("category", "title")},
            },
        ),
        migrations.AddField(
            model_name="service",
            name="type",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                to="services.type",
                verbose_name="Тип услуги",
            ),
        ),
    ]
