# Generated by Django 5.0.4 on 2024-06-14 11:57

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("services", "0002_alter_serviceimage_service_type_service_type"),
    ]

    operations = [
        migrations.AddField(
            model_name="service",
            name="price",
            field=models.JSONField(
                blank=True, null=True, verbose_name="Прайс"
            ),
        ),
    ]
