# Generated by Django 5.0.4 on 2024-06-20 12:16

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        (
            "services",
            "0004_service_experience_service_place_of_provision_and_more",
        ),
    ]

    operations = [
        migrations.AlterField(
            model_name="service",
            name="experience",
            field=models.PositiveIntegerField(
                default=0,
                validators=[django.core.validators.MaxValueValidator(50)],
                verbose_name="Опыт",
            ),
        ),
    ]
