# Generated by Django 5.0.4 on 2024-07-11 08:29

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("services", "0006_alter_service_status"),
    ]

    operations = [
        migrations.AlterField(
            model_name="service",
            name="status",
            field=models.IntegerField(
                choices=[
                    (0, "Draft"),
                    (1, "Moderation"),
                    (2, "Published"),
                    (3, "Hidden"),
                    (4, "Cancelled"),
                    (5, "Changed"),
                ],
                default=0,
                verbose_name="Статус",
            ),
        ),
    ]
