# Generated by Django 5.0.4 on 2024-07-12 06:45

import core.db_utils
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("services", "0007_alter_service_status"),
    ]

    operations = [
        migrations.AlterField(
            model_name="serviceimage",
            name="image",
            field=models.ImageField(
                upload_to="services/",
                validators=[core.db_utils.validate_image],
                verbose_name="Фото к услуге",
            ),
        ),
    ]
