# Generated by Django 5.0.4 on 2024-07-25 09:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("services", "0009_alter_serviceimage_image"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="service",
            options={
                "ordering": ["-created_at"],
                "verbose_name": "Услуга",
                "verbose_name_plural": "Услуги",
            },
        ),
    ]
