# Generated by Django 5.0.4 on 2025-01-04 06:05

import core.db_utils
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("services", "0013_alter_service_address_alter_service_salon_name"),
    ]

    operations = [
        migrations.AlterField(
            model_name="serviceimage",
            name="image",
            field=models.ImageField(
                upload_to=core.db_utils.get_path_to_save_image,
                validators=[core.db_utils.validate_image],
                verbose_name="Фото",
            ),
        ),
    ]
