# Generated by Django 5.0.4 on 2025-01-15 06:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("services", "0014_alter_serviceimage_image"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="type",
            options={
                "verbose_name": "Тип услуги",
                "verbose_name_plural": "Типы услуг",
            },
        ),
    ]
