# Generated by Django 5.0.4 on 2025-02-26 19:35

import django.core.validators
import django.db.models.deletion
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("services", "0016_alter_service_status"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="service",
            name="price",
        ),
        migrations.CreateModel(
            name="SubService",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True,
                        db_index=True,
                        null=True,
                        verbose_name="Время создания",
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        auto_now=True, verbose_name="Время изменения"
                    ),
                ),
                (
                    "title",
                    models.CharField(
                        max_length=255, verbose_name="Название услуги"
                    ),
                ),
                (
                    "price",
                    models.DecimalField(
                        decimal_places=2,
                        max_digits=10,
                        validators=[
                            django.core.validators.MinValueValidator(
                                Decimal("0")
                            )
                        ],
                        verbose_name="Стоимость услуги",
                    ),
                ),
                (
                    "main_service",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="price_list_entries",
                        to="services.service",
                        verbose_name="Основная услуга",
                    ),
                ),
            ],
            options={
                "verbose_name": "Услуга прайс-листа",
                "verbose_name_plural": "Услуги прайс-листа",
            },
        ),
    ]
