# Generated by Django 5.0.4 on 2025-02-20 14:11

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("services", "0016_alter_service_status"),
    ]

    operations = [
        migrations.AddField(
            model_name="type",
            name="image",
            field=models.ImageField(
                blank=True,
                null=True,
                upload_to="categories/",
                verbose_name="изображение",
            ),
        ),
    ]
