# Generated by Django 5.0.4 on 2025-02-22 13:19

import core.enums
import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("services", "0016_alter_service_status"),
    ]

    operations = [
        migrations.CreateModel(
            name="SubService",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "title",
                    models.CharField(
                        max_length=core.enums.Limits[
                            "MAX_LENGTH_SUBSERVICE_TITLE"
                        ],
                        verbose_name="Название услуги",
                    ),
                ),
                (
                    "price",
                    models.DecimalField(
                        decimal_places=core.enums.Limits[
                            "USERNAME_MIN_LENGTH"
                        ],
                        max_digits=core.enums.Limits["MAX_DIGITS_PRICE"],
                        validators=[
                            django.core.validators.MinValueValidator(
                                core.enums.Limits["MIN_VALUE_PRICE"]
                            )
                        ],
                        verbose_name="Стоимость услуги",
                    ),
                ),
            ],
            options={
                "verbose_name": "Услуга прайс-листа",
                "verbose_name_plural": "Услуги прайс-листа",
            },
        ),
        migrations.CreateModel(
            name="PriceListEntry",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "main_service",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="price_list_entries",
                        to="services.service",
                        verbose_name="Основная услуга",
                    ),
                ),
                (
                    "sub_service",
                    models.ForeignKey(
                        blank=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="main_services",
                        to="services.subservice",
                        verbose_name="Дополнительные услуги",
                    ),
                ),
            ],
            options={
                "verbose_name": "Запись прайс-листа",
                "verbose_name_plural": "Записи прайс-листов",
            },
        ),
    ]
