# Generated by Django 5.0.4 on 2025-03-03 06:59

import django.core.validators
import django.db.models.deletion
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("services", "0017_type_image"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="service",
            name="price",
        ),
        migrations.CreateModel(
            name="SubService",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "title",
                    models.CharField(
                        max_length=255, verbose_name="Наименование"
                    ),
                ),
                (
                    "price",
                    models.DecimalField(
                        decimal_places=2,
                        max_digits=10,
                        validators=[
                            django.core.validators.MinValueValidator(
                                Decimal("0")
                            )
                        ],
                        verbose_name="Цена",
                    ),
                ),
                (
                    "main_service",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="price_list_entries",
                        to="services.service",
                        verbose_name="Услуга",
                    ),
                ),
            ],
            options={
                "verbose_name": "Позиция прайс-листа",
                "verbose_name_plural": "Позиции прайс-листов",
            },
        ),
    ]
