# Generated by Django 5.0.4 on 2025-03-04 12:33

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("services", "0018_remove_service_price_subservice"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="service",
            options={
                "default_related_name": "services",
                "ordering": ["-created_at"],
                "verbose_name": "Услуга",
                "verbose_name_plural": "Услуги",
            },
        ),
    ]
