# Generated by Django 5.0.4 on 2025-07-07 07:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("services", "0019_alter_service_options"),
        ("services", "0019_alter_type_image"),
    ]

    operations = []
