# Generated by Django 5.0.4 on 2025-12-05 10:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("categories", "0001_initial"),
        ("services", "0020_merge_20250707_1003"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="service",
            name="type",
        ),
        migrations.AddField(
            model_name="service",
            name="category",
            field=models.ManyToManyField(
                related_name="services",
                to="categories.category",
                verbose_name="Категория",
            ),
        ),
        migrations.DeleteModel(
            name="Type",
        ),
    ]
