# Generated by Django 5.0.4 on 2025-12-12 12:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("services", "0021_remove_service_type_service_category_delete_type"),
    ]

    operations = [
        migrations.AddField(
            model_name="serviceimage",
            name="title_photo",
            field=models.BooleanField(
                default=False, verbose_name="Заглавная фотография"
            ),
        ),
    ]
