# Generated by Django 5.0.4 on 2025-12-22 05:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("services", "0022_serviceimage_title_photo"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="serviceimage",
            name="main_photo",
        ),
    ]
