# Generated by Django 5.0.4 on 2025-11-26 06:43

import core.db_utils
import core.enums
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []  # type: ignore

    operations = [
        migrations.CreateModel(
            name="Category",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "title",
                    models.CharField(
                        max_length=core.enums.Limits["MAX_LENGTH_FIRST_NAME"],
                        verbose_name="Название",
                    ),
                ),
                (
                    "image",
                    models.FileField(
                        blank=True,
                        null=True,
                        upload_to="categories/",
                        validators=[core.db_utils.validate_svg],
                        verbose_name="изображение",
                    ),
                ),
                (
                    "parent",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="subcategories",
                        to="categories.category",
                        verbose_name="Высшая категория",
                    ),
                ),
            ],
            options={
                "verbose_name": "Категория объявления",
                "verbose_name_plural": "Категории объявлений",
                "ordering": ["parent_id", "id"],
            },
        ),
    ]
