name: sunny_ekb

services:
  db:
    container_name: db
    image: postgres:16.1-alpine
    volumes:
      - sunny_ekb_data:/var/lib/postgresql/data/
    env_file:
      - ./.env
    ports:
      - "5432:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U $${POSTGRES_USER} -d $${POSTGRES_DB}"]
      interval: 3s
      timeout: 3s
      retries: 5
    restart: unless-stopped

  nginx:
    container_name: nginx
    image: nginx:1.21.3-alpine
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx_loc.conf:/etc/nginx/conf.d/default.conf
      - sunny_static_value:/var/html/static/
      - sunny_media_value:/var/html/media/
      - ./certbot/letsencrypt:/etc/letsencrypt:ro
    depends_on:
      - backend

  redis:
    container_name: redis
    image: redis:alpine3.18
    restart: unless-stopped
    ports:
      - "6379:6379"
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 5s
      timeout: 3s
      retries: 5

  celery:
    container_name: celery
    build:
      context: .
    restart:
      unless-stopped
    command: |
      celery -A config worker
      -n default
      -Q default
      -E
      -l INFO
      --time-limit 600
      --max-tasks-per-child 100
      --prefetch-multiplier 1
    env_file:
      - .env

  flower:
    container_name: flower
    image: mher/flower
    command: ['celery', '--broker=redis://redis:6379/0', 'flower', '--port=5555', '--url_prefix=/flower']

  backend:
    container_name: backend
    build:
      context: .
    restart: unless-stopped
    volumes:
      - sunny_static_value:/app/static/
      - sunny_media_value:/app/media/
    env_file:
      - ./.env
    command:
      - /bin/sh
      - -c
      - |
        python manage.py collectstatic -c --noinput
        python manage.py makemigrations
        python manage.py migrate
        python3 -m daphne -b 0.0.0.0 -p 8000 config.asgi:application
    depends_on:
      db:
        condition: service_healthy
      redis:
        condition: service_healthy

volumes:
  sunny_static_value:
  sunny_media_value:
  sunny_ekb_data:
