version: '3.8'

services:
  db:
    image: postgres:16.1-alpine
    restart: always
    volumes:
      - sunny_ekb_data:/var/lib/postgresql/data/
    env_file:
      - ./.env

  nginx:
    image: nginx:1.21.3-alpine
    container_name: nginx
    ports:
      - "80:80"
    volumes:
      - ./nginx.conf:/etc/nginx/conf.d/default.conf
      - sunny_static_value:/var/html/static/
      - sunny_media_value:/var/html/media/
    depends_on:
      - backend

  backend:
    build:
      context: .
    restart: always
    volumes:
      - sunny_static_value:/app/static/
      - sunny_media_value:/app/media/
    depends_on:
      - db
    ports:
      - "8000:8000"
    env_file:
      - ./.env
    command: python3 manage.py runserver 0.0.0.0:8000

volumes:
  sunny_static_value:
  sunny_media_value:
  sunny_ekb_data:
