# Generated by Django 5.0.4 on 2024-08-23 08:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0003_favorites"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="favorites",
            options={
                "ordering": ["user", "content_type"],
                "verbose_name": "Избранное",
                "verbose_name_plural": "Избранное",
            },
        ),
    ]
