# Generated by Django 5.0.4 on 2024-09-23 04:58

from django.db import migrations, models

import core.db_utils


class Migration(migrations.Migration):
    dependencies = [
        ("users", "0004_alter_favorites_options"),
    ]

    operations = [
        migrations.AddField(
            model_name="customuser",
            name="photo",
            field=models.ImageField(
                blank=True,
                null=True,
                upload_to=core.db_utils.user_photo_path,
                validators=[core.db_utils.validate_image],
                verbose_name="Фото",
            ),
        ),
    ]
