# Generated by Django 5.0.4 on 2024-10-18 17:24

from django.db import migrations, models

import core.db_utils


class Migration(migrations.Migration):
    dependencies = [
        ("users", "0007_alter_customuser_avatar"),
    ]

    operations = [
        migrations.AlterField(
            model_name="customuser",
            name="avatar",
            field=models.ImageField(
                blank=True,
                null=True,
                upload_to=core.db_utils.user_photo_path,
                validators=[core.db_utils.validate_image],
                verbose_name="Фото",
            ),
        ),
    ]
