# Generated by Django 5.0.4 on 2024-12-18 12:13

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0009_verificationtoken"),
    ]

    operations = [
        migrations.AlterField(
            model_name="verificationtoken",
            name="token",
            field=models.UUIDField(
                default=uuid.UUID("144ba4c4-47b5-40c6-be8c-8ddd61f195cf")
            ),
        ),
    ]
