# Generated by Django 5.0.4 on 2024-12-19 07:58

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("users", "0011_alter_verificationtoken_token_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="verificationtoken",
            name="created_at",
            field=models.DateTimeField(
                auto_now_add=True,
                db_index=True,
                default="2001-01-01 03:17:10.314842-04:00",
                verbose_name="Время создания",
            ),
            preserve_default=False,
        ),
    ]
