# Generated by Django 5.0.4 on 2025-01-17 12:25

import phonenumber_field.modelfields
from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("users", "0012_verificationtoken_created_at"),
    ]

    operations = [
        migrations.AlterField(
            model_name="customuser",
            name="phone",
            field=phonenumber_field.modelfields.PhoneNumberField(
                max_length=12,
                region=None,
                unique=True,
                verbose_name="Номер телефона",
            ),
        ),
    ]
