# Generated by Django 5.0.4 on 2025-01-10 13:16

import core.db_utils
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0012_verificationtoken_created_at"),
    ]

    operations = [
        migrations.AlterField(
            model_name="customuser",
            name="avatar",
            field=models.ImageField(
                blank=True,
                null=True,
                upload_to=core.db_utils.get_path_to_save_image,
                validators=[core.db_utils.validate_image],
                verbose_name="Фото",
            ),
        ),
    ]
