# Generated by Django 5.0.4 on 2024-07-11 12:19

import core.enums
import django.core.validators
import django.db.models.deletion
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Ad",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True,
                        db_index=True,
                        null=True,
                        verbose_name="Время создания",
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        auto_now=True, verbose_name="Время изменения"
                    ),
                ),
                (
                    "title",
                    models.CharField(max_length=250, verbose_name="Название"),
                ),
                (
                    "description",
                    models.TextField(max_length=500, verbose_name="Описание"),
                ),
                (
                    "status",
                    models.IntegerField(
                        choices=[
                            (0, "Draft"),
                            (1, "Moderation"),
                            (2, "Published"),
                            (3, "Hidden"),
                            (4, "Cancelled"),
                            (5, "Changed"),
                        ],
                        default=0,
                        verbose_name="Статус",
                    ),
                ),
                (
                    "category",
                    models.CharField(
                        choices=[("Обувь", "Shoes"), ("Одежда", "Clothes")],
                        max_length=core.enums.Limits["MAX_LENGTH_FIRST_NAME"],
                        verbose_name="Категория",
                    ),
                ),
                (
                    "price",
                    models.DecimalField(
                        decimal_places=2,
                        max_digits=10,
                        validators=[
                            django.core.validators.MinValueValidator(
                                Decimal("0"), "Цена не может быть меньше 0"
                            )
                        ],
                        verbose_name="Цена",
                    ),
                ),
                (
                    "provider",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Исполнитель",
                    ),
                ),
            ],
            options={
                "verbose_name": "Объявление",
                "verbose_name_plural": "Объявления",
            },
        ),
        migrations.CreateModel(
            name="AdImage",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "image",
                    models.ImageField(
                        upload_to="ads/", verbose_name="Фото к объявлению"
                    ),
                ),
                (
                    "service",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="images",
                        to="ads.ad",
                        verbose_name="Объявление",
                    ),
                ),
            ],
            options={
                "verbose_name": "Фото к объявлению",
                "verbose_name_plural": "Фото к объявлениям",
            },
        ),
    ]
