# Generated by Django 5.0.4 on 2024-07-12 07:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("ads", "0002_alter_adimage_image"),
    ]

    operations = [
        migrations.RenameField(
            model_name="adimage",
            old_name="service",
            new_name="ad",
        ),
    ]
