# Generated by Django 5.0.4 on 2024-07-24 12:22

import core.enums
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("ads", "0003_rename_service_adimage_ad"),
    ]

    operations = [
        migrations.AddField(
            model_name="ad",
            name="condition",
            field=models.CharField(
                choices=[("Б/у", "Used"), ("Новый", "New")],
                default="Б/у",
                max_length=core.enums.Limits["MAX_LENGTH_ADVMNT_STATE"],
                verbose_name="Состояние",
            ),
        ),
    ]
