# Generated by Django 5.0.4 on 2024-07-24 14:22

import core.enums
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("ads", "0004_ad_condition"),
    ]

    operations = [
        migrations.AlterField(
            model_name="ad",
            name="category",
            field=models.CharField(
                choices=[
                    ("Личные вещи", "Personal Items"),
                    ("Электроника", "Electronics"),
                    ("Для детей", "Children"),
                    ("Хобби и отдых", "Hobbies"),
                    ("Животные", "Pets"),
                    ("Другое", "Other"),
                ],
                max_length=core.enums.Limits["MAX_LENGTH_FIRST_NAME"],
                verbose_name="Категория",
            ),
        ),
        migrations.CreateModel(
            name="AdvCategory",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "title",
                    models.CharField(
                        max_length=core.enums.Limits["MAX_LENGTH_FIRST_NAME"],
                        verbose_name="Название",
                    ),
                ),
                (
                    "parent",
                    models.ForeignKey(
                        blank=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="subcategories",
                        to="ads.advcategory",
                        verbose_name="Высшая категория",
                    ),
                ),
            ],
            options={
                "verbose_name": "Категория объявления",
                "verbose_name_plural": "Категории объявлений",
            },
        ),
    ]
