# Generated by Django 5.0.4 on 2024-07-25 10:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "ads",
            "0006_rename_advcategory_adcategory_alter_ad_options_and_more",
        ),
    ]

    operations = [
        migrations.AlterField(
            model_name="adcategory",
            name="parent",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="subcategories",
                to="ads.adcategory",
                verbose_name="Высшая категория",
            ),
        ),
    ]
