# Generated by Django 5.0.4 on 2024-07-25 11:11

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("ads", "0008_alter_adcategory_parent"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="adcategory",
            options={
                "ordering": ["parent_id", "title"],
                "verbose_name": "Категория объявления",
                "verbose_name_plural": "Категории объявлений",
            },
        ),
    ]
