# Generated by Django 5.0.4 on 2024-07-26 07:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("ads", "0010_alter_adcategory_options"),
    ]

    operations = [
        migrations.RenameModel(
            old_name="AdCategory",
            new_name="Category",
        ),
        migrations.AddField(
            model_name="ad",
            name="category",
            field=models.ManyToManyField(
                related_name="ads", to="ads.category", verbose_name="Kатегории"
            ),
        ),
    ]
