# Generated by Django 5.0.4 on 2025-01-15 06:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("ads", "0012_alter_adimage_image"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="category",
            options={
                "verbose_name": "Категория объявления",
                "verbose_name_plural": "Категории объявлений",
            },
        ),
    ]
