# Generated by Django 5.0.4 on 2025-01-24 11:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("ads", "0013_alter_category_options"),
    ]

    operations = [
        migrations.AlterField(
            model_name="ad",
            name="status",
            field=models.IntegerField(
                choices=[
                    (0, "Draft"),
                    (1, "Moderation"),
                    (2, "Published"),
                    (3, "Hidden"),
                ],
                default=0,
                verbose_name="Статус",
            ),
        ),
    ]
