# Generated by Django 5.0.4 on 2025-03-04 12:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("ads", "0015_category_image"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="ad",
            options={
                "default_related_name": "ads",
                "ordering": ["-created_at"],
                "verbose_name": "Объявление",
                "verbose_name_plural": "Объявления",
            },
        ),
    ]
