# Generated by Django 5.0.4 on 2025-06-24 08:57

import core.db_utils
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("ads", "0015_category_image"),
    ]

    operations = [
        migrations.AlterField(
            model_name="category",
            name="image",
            field=models.FileField(
                blank=True,
                null=True,
                upload_to="categories/",
                validators=[core.db_utils.validate_svg],
                verbose_name="изображение",
            ),
        ),
    ]
