# Generated by Django 5.0.4 on 2025-07-07 07:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("ads", "0016_alter_ad_options"),
        ("ads", "0016_alter_category_image"),
    ]

    operations = []
