# Generated by Django 5.0.4 on 2025-11-28 14:09

import core.enums
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("ads", "0017_merge_0016_alter_ad_options_0016_alter_category_image"),
    ]

    operations = [
        migrations.AddField(
            model_name="ad",
            name="address",
            field=models.CharField(
                blank=True,
                max_length=core.enums.Limits["MAX_LENGTH_ADVMNT_TITLE"],
                null=True,
                verbose_name="Адрес",
            ),
        ),
    ]
