# Generated by Django 5.0.4 on 2025-12-05 10:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("ads", "0018_ad_address"),
        ("categories", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="ad",
            name="category",
            field=models.ManyToManyField(
                related_name="ads",
                to="categories.category",
                verbose_name="Kатегории",
            ),
        ),
        migrations.DeleteModel(
            name="Category",
        ),
    ]
