# Generated by Django 5.0.4 on 2025-12-12 12:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("ads", "0019_alter_ad_category_delete_category"),
    ]

    operations = [
        migrations.AddField(
            model_name="adimage",
            name="title_photo",
            field=models.BooleanField(
                default=False, verbose_name="Заглавная фотография"
            ),
        ),
    ]
