# Generated by Django 5.0.4 on 2024-08-06 09:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("comments", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="comment",
            name="created_at",
            field=models.DateTimeField(
                auto_now_add=True,
                db_index=True,
                null=True,
                verbose_name="Время создания",
            ),
        ),
        migrations.AddField(
            model_name="comment",
            name="updated_at",
            field=models.DateTimeField(
                auto_now=True, verbose_name="Время изменения"
            ),
        ),
    ]
