# Generated by Django 5.0.4 on 2024-08-23 06:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "comments",
            "0003_alter_comment_options_alter_commentimage_options_and_more",
        ),
    ]

    operations = [
        migrations.AddField(
            model_name="comment",
            name="status",
            field=models.IntegerField(
                choices=[(0, "Draft"), (1, "Moderation"), (2, "Published")],
                default=0,
                verbose_name="Статус комментария",
            ),
        ),
    ]
