# Generated by Django 5.0.4 on 2024-08-23 06:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("comments", "0004_comment_status"),
    ]

    operations = [
        migrations.AlterField(
            model_name="comment",
            name="status",
            field=models.IntegerField(
                choices=[(0, "Draft"), (1, "Published")],
                default=0,
                verbose_name="Статус комментария",
            ),
        ),
    ]
