# Generated by Django 5.0.4 on 2025-01-04 13:58

import core.db_utils
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("comments", "0005_alter_comment_status"),
    ]

    operations = [
        migrations.AlterField(
            model_name="commentimage",
            name="image",
            field=models.ImageField(
                upload_to=core.db_utils.get_path_to_save_image,
                validators=[core.db_utils.validate_image],
                verbose_name="Фото",
            ),
        ),
    ]
