# Generated by Django 5.0.4 on 2025-02-17 13:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("comments", "0006_alter_commentimage_image"),
    ]

    operations = [
        migrations.AlterField(
            model_name="comment",
            name="status",
            field=models.IntegerField(
                choices=[(0, "Draft"), (1, "Published"), (2, "Moderation")],
                default=0,
                verbose_name="Статус комментария",
            ),
        ),
    ]
