# Generated by Django 5.0.4 on 2025-12-12 12:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("comments", "0007_alter_comment_status"),
    ]

    operations = [
        migrations.AddField(
            model_name="commentimage",
            name="title_photo",
            field=models.BooleanField(
                default=False, verbose_name="Заглавная фотография"
            ),
        ),
    ]
