# Generated by Django 5.0.4 on 2026-01-17 16:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("comments", "0008_commentimage_title_photo"),
    ]

    operations = [
        migrations.AlterField(
            model_name="comment",
            name="status",
            field=models.IntegerField(
                choices=[(1, "Published"), (2, "Moderation")],
                default=2,
                verbose_name="Статус комментария",
            ),
        ),
    ]
